/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Chappie
 */
public class Contacto extends javax.swing.JFrame {

    /**
     * Creates new form Contacto
     */
    public Contacto() {
        initComponents();
        ocultar();
    }
public void ocultar()
{
    setLocationRelativeTo(null);
    Buscador.setText("Buscar...");
    Dperfil.setVisible(false);
    Ddetalles.setVisible(false);
    Resul.setVisible(false);
    sepa1.setVisible(false);
    sepa2.setVisible(false);
    perfil.setVisible(false);
    detalles.setVisible(false);
    nombre.setVisible(false);
    foto.setVisible(false);
    Buscar.requestFocus();
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarraLateral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Buscador = new javax.swing.JTextField();
        Buscar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Resul = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        detalles = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        sepa2 = new javax.swing.JSeparator();
        sepa1 = new javax.swing.JSeparator();
        Dperfil = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Ddetalles = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Nuevabusq = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        BarraLateral.setBackground(new java.awt.Color(51, 51, 51));
        BarraLateral.setForeground(new java.awt.Color(102, 102, 102));
        BarraLateral.setMaximumSize(new java.awt.Dimension(299, 365));
        BarraLateral.setMinimumSize(new java.awt.Dimension(299, 365));
        BarraLateral.setPreferredSize(new java.awt.Dimension(299, 365));
        BarraLateral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraLateralMouseDragged(evt);
            }
        });
        BarraLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraLateralMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BarraLateralMouseReleased(evt);
            }
        });
        BarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Left_15px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarraLateral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Gotham Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contactos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarraLateral.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 5, 110, 20));

        Buscador.setBackground(new java.awt.Color(51, 51, 51));
        Buscador.setForeground(new java.awt.Color(255, 255, 255));
        Buscador.setText("Buscar...");
        Buscador.setBorder(null);
        Buscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BuscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BuscadorFocusLost(evt);
            }
        });
        BarraLateral.add(Buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 40));

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Search_30px.png"))); // NOI18N
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });
        BarraLateral.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 40, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        BarraLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 230, 10));

        Resul.setBackground(new java.awt.Color(204, 204, 204));
        Resul.setFont(new java.awt.Font("Gotham Light", 0, 18)); // NOI18N
        Resul.setForeground(new java.awt.Color(51, 51, 51));
        Resul.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Resul.setText("Chappie");
        Resul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Resul.setOpaque(true);
        Resul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResulMouseClicked(evt);
            }
        });
        BarraLateral.add(Resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, 30));

        Contenido.setBackground(new java.awt.Color(0, 0, 0));
        Contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Delete_15px_1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Contenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 28, 32));

        nombre.setBackground(new java.awt.Color(0, 0, 0));
        nombre.setFont(new java.awt.Font("Gotham Light", 0, 36)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Chappie");
        nombre.setOpaque(true);
        Contenido.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 30));

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Person_100px.png"))); // NOI18N
        Contenido.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, 120));

        detalles.setBackground(new java.awt.Color(0, 0, 0));
        detalles.setFont(new java.awt.Font("Gotham Light", 0, 18)); // NOI18N
        detalles.setForeground(new java.awt.Color(255, 255, 255));
        detalles.setText("Detalles");
        detalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detalles.setOpaque(true);
        detalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detallesMouseClicked(evt);
            }
        });
        Contenido.add(detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 100, 20));

        perfil.setBackground(new java.awt.Color(0, 0, 0));
        perfil.setFont(new java.awt.Font("Gotham Light", 0, 18)); // NOI18N
        perfil.setForeground(new java.awt.Color(255, 255, 255));
        perfil.setText("Perfil");
        perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perfil.setOpaque(true);
        perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perfilMouseClicked(evt);
            }
        });
        Contenido.add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, 20));
        Contenido.add(sepa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 90, 10));
        Contenido.add(sepa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, 10));

        Dperfil.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Gotham Light", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombres");
        jLabel10.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Gotham Light", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Xxxxx Xxxxx");
        jLabel11.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Gotham Light", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Apellidos");
        jLabel12.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Gotham Light", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Xxxxxxx Xxxxxxx");
        jLabel13.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Gotham Light", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fecha de Nacimiento");
        jLabel14.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Gotham Light", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("26/05/1998");
        jLabel15.setOpaque(true);

        javax.swing.GroupLayout DperfilLayout = new javax.swing.GroupLayout(Dperfil);
        Dperfil.setLayout(DperfilLayout);
        DperfilLayout.setHorizontalGroup(
            DperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DperfilLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(DperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DperfilLayout.setVerticalGroup(
            DperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DperfilLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Contenido.add(Dperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 280, 190));

        Ddetalles.setBackground(new java.awt.Color(0, 0, 0));
        Ddetalles.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Gotham Light", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tipo de Usuario");
        jLabel16.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Gotham Light", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Administrador");
        jLabel17.setOpaque(true);

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Gotham Light", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Fecha de Inicio");
        jLabel18.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Gotham Light", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("25/07/2007");
        jLabel19.setOpaque(true);

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Gotham Light", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Oficio");
        jLabel20.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Gotham Light", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Desarrollador");
        jLabel21.setOpaque(true);

        javax.swing.GroupLayout DdetallesLayout = new javax.swing.GroupLayout(Ddetalles);
        Ddetalles.setLayout(DdetallesLayout);
        DdetallesLayout.setHorizontalGroup(
            DdetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DdetallesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DdetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DdetallesLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DdetallesLayout.createSequentialGroup()
                        .addGroup(DdetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addContainerGap(89, Short.MAX_VALUE))))
        );
        DdetallesLayout.setVerticalGroup(
            DdetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DdetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Contenido.add(Ddetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 270, 220));

        Nuevabusq.setBackground(new java.awt.Color(0, 0, 0));
        Nuevabusq.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        Nuevabusq.setForeground(new java.awt.Color(255, 255, 255));
        Nuevabusq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nuevabusq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Search_Property_104px.png"))); // NOI18N
        Nuevabusq.setText("Nueva Busqueda");
        Nuevabusq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Nuevabusq.setOpaque(true);
        Nuevabusq.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Contenido.add(Nuevabusq, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 160, 170));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .addComponent(BarraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xx,xy;
    private void BarraLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraLateralMousePressed
        setOpacity((float)0.8);
                xx=evt.getX();
                xy=evt.getY();
    }//GEN-LAST:event_BarraLateralMousePressed

    private void BarraLateralMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraLateralMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_BarraLateralMouseReleased

    private void BarraLateralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraLateralMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_BarraLateralMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void ResulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResulMouseClicked
    perfil.setVisible(true);
    Buscador.setText("Buscar...");
    Dperfil.setVisible(true);
    Ddetalles.setVisible(false);
    Resul.setVisible(false);
    sepa1.setVisible(true);
    sepa2.setVisible(true);
    perfil.setVisible(true);
    detalles.setVisible(true);
    nombre.setVisible(true);
    foto.setVisible(true);
    Buscar.requestFocus();
    Nuevabusq.setVisible(false);
       
    }//GEN-LAST:event_ResulMouseClicked

    private void BuscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscadorFocusGained
      if(("Buscar...").equals(Buscador.getText())){
          Buscador.setText("");
      }
    }//GEN-LAST:event_BuscadorFocusGained

    private void BuscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscadorFocusLost
        if(("").equals(Buscador.getText())){
          Buscador.setText("Buscar...");
      }
    }//GEN-LAST:event_BuscadorFocusLost

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
        if(("Chappie").equals(Buscador.getText())){
             Resul.setVisible(true);
        }
    }//GEN-LAST:event_BuscarMouseClicked

    private void detallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detallesMouseClicked
    perfil.setVisible(true);
    Buscador.setText("Buscar...");
    Dperfil.setVisible(false);
    Ddetalles.setVisible(true);
    Resul.setVisible(false);
    Buscar.requestFocus();
    Nuevabusq.setVisible(false);
        
        
        
    }//GEN-LAST:event_detallesMouseClicked

    private void perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseClicked
    perfil.setVisible(true);
    Buscador.setText("Buscar...");
    Dperfil.setVisible(true);
    Ddetalles.setVisible(false);
    Resul.setVisible(false);
    Buscar.requestFocus();
    Nuevabusq.setVisible(false);
    }//GEN-LAST:event_perfilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraLateral;
    private javax.swing.JTextField Buscador;
    private javax.swing.JLabel Buscar;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Ddetalles;
    private javax.swing.JPanel Dperfil;
    private javax.swing.JLabel Nuevabusq;
    private javax.swing.JLabel Resul;
    private javax.swing.JLabel detalles;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel perfil;
    private javax.swing.JSeparator sepa1;
    private javax.swing.JSeparator sepa2;
    // End of variables declaration//GEN-END:variables
}
